name: SkyMine
version: '${project.version}'
main: com.github.cutealpacafr.skymine.SkyMine
api-version: 1.18
commands:
  kit:
    description: Your description
    usage: /kit
  ZW:
    description: Your description
    usage: /zw
  Scroll:
    description: give you scroll
    usage: /Scroll
  fr:
    description: Your description
    usage: /fr
  Titan:
    description: spawns titan
    usage: /Titan
  AC:
    description: Your description
    usage: /ac
  Skilra:
    description: SKilllllra
    usage: /Skilra
  TD:
    description: the dupe!
    usage: /TD
  SE:
    description: se
    usage: /SE
  levi:
    description: leo should kims
    usage: /levi
  TE:
    description: aragorn is bald
    usage: /TE
  VD:
    description: filperrrr
    usage: /VD